package threads;

public class ResultTask extends Thread {
    public void run(){
        System.out.println("Result generated by: " +
                Thread.currentThread().getName());
    }
    public static void main(String[] args) {
        ResultTask t1 = new ResultTask();
        t1.run(); // ℹ Normal Execution -> Always the main thread
        t1.start(); // 🟢 Multi Threading -> T-0, T-1, & so on
        // ℹ start() internally calls run()
        // ☑ Thread cannot be started twice
    }
}